# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-17 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('run_time', models.IntegerField()),
                ('sum_case', models.IntegerField()),
                ('run_case', models.IntegerField()),
                ('skip_case', models.IntegerField()),
            ],
        ),
    ]
