# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
