# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20190818_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_cases', models.IntegerField()),
                ('fail_cases', models.IntegerField()),
                ('error_cases', models.IntegerField()),
                ('skip_cases', models.IntegerField()),
            ],
        ),
    ]
